apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-codegen-dummy-11 
  janus-idp.io/tekton: test-codegen-dummy-11
  backstage.io/kubernetes-id: test-codegen-dummy-11
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-codegen-dummy-11
resources: 
- application-dev.yaml